# Generated by Django 3.2.12 on 2022-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_muted_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('personal', 'О себе'), ('tech', 'Технологии'), ('club', 'Для других членов Клуба я...'), ('hobbies', 'Хобби'), ('know', 'Разбираюсь в'), ('other', 'Остальное')], default='other', max_length=32),
        ),
    ]
